import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import SideMenubar from "@/components/SideMenubar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SideMenubar />
        <div className="px-5 pt-6 w-full">
        {children}
        </div>
      </body>
    </html>
  );
}
